test_main.o: test_main.cpp page_table_tests.cpp tlb_tests.cpp data_cache_tests.cpp ../page_table.h ../page_table.cpp
	g++ -g -Wall test_main.cpp page_table_tests.cpp tlb_tests.cpp data_cache_tests.cpp ../page_table.h ../page_table.cpp -o test_main.o



